spring.application.name=programmermuda-product-auth

server.port=8083

spring.datasource.url=jdbc:postgresql://localhost:5432/auth
spring.datasource.username=sar_psql
spring.datasource.password=rahasia

spring.jpa.properties.hibernate.jdbc.dialect=org.hibernate.dialect.PostgresSQLDialect

spring.jpa.hibernate.ddl-auto=update

security.jwt.secret-key=a987bfe2aeed60e1979549852812de52b04d96b9a9dfe3a17a51f757c8fdc480
security.jwt.expiration-time=3600000
