spring.application.name=programmermuda-project-product

server.port=8081
# Mengaktifkan pemeriksaan lokasi template
spring.thymeleaf.check-template-location=true

# Menentukan lokasi template
spring.thymeleaf.prefix=classpath:/templates/

# Menentukan ekstensi default untuk file template
spring.thymeleaf.suffix=.html

# URL back end
auth.url=http://localhost:8089

